### ISSUE TITLE
Firmware installation guide errata

### ISSUE THREAD

**Issue by aeberbach** [TheByteAttic/AgonLight#1]
- must install the Windows CP210x USB drivers (or there is no virtual COM port for Arduino to connect)
- must select "ESP32 Dev Module" as board
- must install the ESP32Time library
- must not allow Arduino to update the FabGL library to version 1.0.9

**Comment by nihirash** [comment]
Flashing VDP. 

For mac systems there can be added small remark - if you got error:
```
Changing baud rate to 921600
Changed.
Configuring flash size...
An error occurred while uploading the sketch
```

Change speed to 115200 and you'll got flashing process working correctly.

**Comment by TheByteAttic** [comment]
Please post at the firmware repos.
