### ISSUE TITLE
Documentation for using SDCC instead of ZDC?

### ISSUE THREAD

**Issue by spth** [TheByteAttic/AgonLight#3]
Since the documentation at https://github.com/breakintoprogram/agon-docs does not have an issue tracker, I'm posting this here: Currently ZDS C is the only option mentioned for programming in C. The free Small Device c compiler (SDCC) has the ez80_z80 backend (which uses the eZ80 in Z80 mode). IMO, it would make sense to mention it in the documentation, and maybe provide a simple "Hello, world!" or such example for the AgonLight.

**Comment by TheByteAttic** [comment]
I can't help, and not a hardware issue.
