### ISSUE TITLE
Developpers forum for the Agon Light

### ISSUE THREAD

**Issue by DjPoke** [TheByteAttic/AgonLight#4]
Hi,
It can be usefull to make a developpers forum for this machine.

**Comment by TheByteAttic** [comment]
There are several discord servers and facebook groups.

**Comment by funkheld** [comment]
agon-4th-24 with fab-agon-emulator-v0.9.50-windows-x64

Hi good afternoon.
I am 75 years old and come from Germany.
I play with agon 8bit emulator with the forth24.
I have already created some programs.
a wonderful forth.

I would be happy if you could also see some sprites as a demo.

Thanks.
greeting

**Comment by funkheld** [comment]
Hi good afternoon.
Here is a small forth24 demo with fab-agon-emulator.exe
keys with up, down, left, right.

char graphic:
"ABCDE"
"12345"
"67890"

With key up/down the digits "12345" always go up 4 bits and down 4 bits. what is that about please?

Thanks.
greeting

--------------------------------------------
S" agon.4th" included

57 CONSTANT KEY-UP
41 CONSTANT KEY-DOWN
25 CONSTANT KEY-LEFT
121 CONSTANT KEY-RIGHT
98 CONSTANT KEY-SPACE
112 CONSTANT KEY-ESC
48 CONSTANT KEY-1
49 CONSTANT KEY-2
17 CONSTANT KEY-3


variable x
variable y
variable x1
variable y1
variable x2
variable y2

100 x !
320 y !

100 x1 !
352 y1 !

100 x2 !
384 y2 !

: halt
2000 0 do loop ;

: text
x2 @ y2 @  moveto 36 gcol ." ABCDE"
x1 @ y1 @  moveto 20 gcol ." 12345"
x @ y @  moveto 44 gcol ." 67890"  flip ;

: viereck
0 0 moveto 32 gcol 800 800 line
500 500 moveto 40 gcol 600 600 box ;

: plottetext
12 emit
viereck
text ;

: mainloop
   136 mode
   16 bg
   5 emit
   page
   plottetext  
   
    do
	
	VWAIT
	KEY-UP KEYCODE? IF y @ 4 + y ! y1 @ 4 + y1 ! y2 @ 4 + y2 ! plottetext THEN
	KEY-DOWN KEYCODE? IF y @ 4 - y ! y1 @ 4 - y1 ! y2 @ 4 - y2 ! plottetext THEN
	KEY-RIGHT KEYCODE? IF x @ 4 + x ! x1 @ 4 + x1 ! x2 @ 4 + x2 ! plottetext THEN
	KEY-LEFT KEYCODE? IF x @ 4 - x ! x1 @ 4 - x1 ! x2 @ 4 - x2 ! plottetext THEN
	
    loop ;
	
: run
mainloop ;	
----------------------------------------------------------------------

**Comment by funkheld** [comment]
![fehler](https://github.com/TheByteAttic/AgonLight/assets/163685810/61053652-fcb2-41af-b929-42caf5f7775d)

**Comment by TheByteAttic** [comment]
Cool, thanks!
