### ISSUE TITLE
Lag on the keyboard

### ISSUE THREAD

**Issue by fotosyn** [TheByteAttic/AgonLight#5]
I find I need to press return twice on this board to input detail and the programs run really slowly. It's almost like the interrup / update is triggered by pressing return key on my Keyboard. Any ideas?

Agon is an Olimex Agon Light 2 version

UsingJUSTOP PS/2 Compatible keyboard. Lag is even worse if I use a plug in adapter. Connected to USB port on desktop / Mac is easier but the lag is still there.

**Comment by oldpatientsea** [comment]
I'm going to guess you're running an incompatible version of BASIC with the version of MOS you have installed on the board.

What version of the firmware (MOS/VDP) do you have installed? They should be visible at the top of the screen.

What does `*VERSION` tell you when you run it in BASIC?

**Comment by oldpatientsea** [comment]
![version](https://github.com/TheByteAttic/AgonLight/assets/129397698/d452048a-7c09-470b-af55-af9bfe2d2050)

Here's an example of what I mean. I believe recent Olimex boards will be shipping with 1.04 RC2 firmware. You can get BASIC 1.06 from https://github.com/breakintoprogram/agon-bbc-basic

**Comment by fotosyn** [comment]
> ![version](https://github.com/TheByteAttic/AgonLight/assets/129397698/d452048a-7c09-470b-af55-af9bfe2d2050)
> 
> 
> 
> Here's an example of what I mean. I believe recent Olimex boards will be shipping with 1.04 RC2 firmware. You can get BASIC 1.06 from https://github.com/breakintoprogram/agon-bbc-basic

Thank you. I have uograded from 1.04RC1 to RC2 and it has resolved this issue. bBC Basic is 1.06

Seems much more responsive now! Thanks
