### ISSUE TITLE
BBC BASIC (Z80) updated to v 5.00

### ISSUE THREAD

**Issue by rtrussell** [TheByteAttic/AgonLight#7]
This is just a heads-up that I have recently updated the [Z80 version of BBC BASIC](https://github.com/rtrussell/BBCZ80.git) from v3.00 to v5.00, which incorporates most of the features of Acorn's ARM BASIC V plus some extensions of my own.  This has meant increasing the size from about 12 Kbytes to 16 Kbytes.  It is still at a Beta release stage but perhaps it's something in which you might be interested.

**Comment by TheByteAttic** [comment]
Great, thanks! Please let them know about it over at the developers group or discord.

**Comment by rtrussell** [comment]
> Please let them know about it over at the developers group or discord.

I'm not familiar with either of those places so I cannot comply.

**Comment by TheByteAttic** [comment]
We have two systems using BBC BASIC: Agon and CERBERUS. In both cases, Dean Belfield is the lead developer. You can find the respective developers' groups here:
https://www.facebook.com/groups/agoncomputer
https://www.facebook.com/groups/cerberuscomputer
Cheers!

**Comment by TheByteAttic** [comment]
I posted your message in both groups.

**Comment by rtrussell** [comment]
> You can find the respective developers' groups here:

OK, I will post there.
