### ISSUE TITLE
AgonLight2 not booting MOS

### ISSUE THREAD

**Issue by oshaboy** [TheByteAttic/AgonLight#8]
Hello I got an AgonLight2 ages ago and it has worked before but now it's stuck displaying "Agon Quark VPD Version 1.02" and a blinking cursor. Never succeeding at booting into MOS

What could possibly be the issue with it?

**Comment by TheByteAttic** [comment]
I don't sell Agon Lights, so you must ask your seller or the online communities.

**Comment by oshaboy** [comment]
Can you recommend any online communities for the agonlight who can help me?

**Comment by TheByteAttic** [comment]
https://www.facebook.com/groups/agoncomputer

**Comment by oshaboy** [comment]
Thank you
